name: Debug APK Build Process
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  debug-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build frontend
      run: npm run build
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        
    - name: Accept Android licenses
      run: echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
      
    - name: Pre-build Directory Check
      run: |
        echo "=== Pre-build Directory Structure ==="
        ls -la android/
        ls -la android/app/
        ls -la android/app/build/ 2>/dev/null || echo "app/build not found"
        
    - name: Gradle Build with Full Logging
      run: |
        echo "=== Starting Gradle Build with Full Logging ==="
        chmod +x android/gradlew
        cd android
        echo "=== Available Gradle Tasks ==="
        ./gradlew tasks --all | grep -E "(assemble|build|apk)"
        echo "=== Running assembleRelease ==="
        ./gradlew assembleRelease --info --stacktrace 2>&1 | tee ../gradle-build.log
        
    - name: Post-build Complete File Search
      run: |
        echo "=== Post-build Complete File Search ==="
        echo "Searching for ALL APK files in project:"
        find . -name "*.apk" -type f -exec ls -la {} \; 2>/dev/null || echo "No APK files found"
        echo "Searching for ALL .aab files (Android App Bundle):"
        find . -name "*.aab" -type f -exec ls -la {} \; 2>/dev/null || echo "No AAB files found"
        echo "=== Build directories structure ==="
        find android -name "build" -type d -exec echo "Build dir: {}" \; -exec ls -la {} \; 2>/dev/null || echo "No build directories"
        echo "=== All outputs directories ==="
        find android -name "outputs" -type d -exec echo "Outputs dir: {}" \; -exec ls -la {} \; 2>/dev/null || echo "No outputs directories"
        echo "=== Intermediate directories ==="
        find android -path "*/intermediates/*" -name "*.apk" -type f -exec ls -la {} \; 2>/dev/null || echo "No APK in intermediates"
        
    - name: Check Gradle Configuration
      run: |
        echo "=== Checking Gradle Configuration ==="
        echo "Root build.gradle:"
        cat android/build.gradle
        echo "=== App build.gradle ==="
        cat android/app/build.gradle
        echo "=== Gradle Properties ==="
        cat android/gradle.properties 2>/dev/null || echo "No gradle.properties"
        
    - name: Upload Build Logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          gradle-build.log
          android/build/
        if-no-files-found: warn
        
    - name: Final Summary
      run: |
        echo "=== Final Summary ==="
        echo "Build completed. Checking for any generated files:"
        find android -newer android/gradlew -type f -name "*.apk" -o -name "*.aab" 2>/dev/null || echo "No newly generated APK or AAB files found"
        echo "=== All files modified in last 10 minutes ==="
        find android -mmin -10 -type f | head -20